// 🔹 티어 매핑
export const tierMap = {
  IRON: "아이언",
  BRONZE: "브론즈",
  SILVER: "실버",
  GOLD: "골드",
  PLATINUM: "플래티넘",
  EMERALD: "에메랄드",
  DIAMOND: "다이아",
  MASTER: "마스터",
  GRANDMASTER: "그랜드마스터",
  CHALLENGER: "챌린저",
};

// 🔹 라인 매핑
export const positionMap = {
  "TOP": "탑",
  "JUNGLE": "정글",
  "MIDDLE": "미드",
  "MID": "미드",
  "BOTTOM": "원딜",
  "ADC": "원딜",
  "UTILITY": "서포터",
  "SUPPORT": "서포터",
  "NONE": "미정",
  "UNKNOWN": "미정",
  "": "미정"
};

// 🔹 챔피언 매핑
export const championMap = {
  "Aurora": "오로라",
  "Yunara": "유나라",
  "MonkeyKing": "오공",
  "Aatrox": "아트록스",
  "Ahri": "아리",
  "Akali": "아칼리",
  "Alistar": "알리스타",
  "Amumu": "아무무",
  "Anivia": "애니비아",
  "Annie": "애니",
  "Ambessa": "암베사",
  "Aphelios": "아펠리오스",
  "Ashe": "애쉬",
  "AurelionSol": "아우렐리온솔",
  "Azir": "아지르",
  "Bard": "바드",
  "BelVeth": "벨베스",
  "Blitzcrank": "블리츠크랭크",
  "Brand": "브랜드",
  "Braum": "브라움",
  "Briar": "브라이어",
  "Caitlyn": "케이틀린",
  "Camille": "카밀",
  "Cassiopeia": "카시오페아",
  "ChoGath": "초가스",
  "Corki": "코르키",
  "Darius": "다리우스",
  "Diana": "다이애나",
  "DrMundo": "문도박사",
  "Draven": "드레이븐",
  "Ekko": "에코",
  "Elise": "엘리스",
  "Evelynn": "이블린",
  "Ezreal": "이즈리얼",
  "Fiddlesticks": "피들스틱",
  "Fiora": "피오라",
  "Fizz": "피즈",
  "Galio": "갈리오",
  "Gangplank": "갱플랭크",
  "Garen": "가렌",
  "Gnar": "나르",
  "Gragas": "그라가스",
  "Graves": "그레이브즈",
  "Gwen": "그웬",
  "Hecarim": "헤카림",
  "Heimerdinger": "하이머딩거",
  "Hwei": "흐웨이",
  "Illaoi": "일라오이",
  "Irelia": "이렐리아",
  "Ivern": "아이번",
  "Janna": "잔나",
  "JarvanIV": "자르반4세",
  "Jax": "잭스",
  "Jayce": "제이스",
  "Jhin": "진",
  "Jinx": "징크스",
  "KaiSa": "카이사",
  "Kalista": "칼리스타",
  "Karma": "카르마",
  "Karthus": "카서스",
  "Kassadin": "카사딘",
  "Katarina": "카타리나",
  "Kayle": "케일",
  "Kayn": "케인",
  "Kennen": "케넨",
  "KhaZix": "카직스",
  "Kindred": "킨드레드",
  "Kled": "클레드",
  "KogMaw": "코그모",
  "LeBlanc": "르블랑",
  "LeeSin": "리신", // LEE SIN은 영어로 유지되지만, 한글로 표시됨
  "Leona": "레오나",
  "Lillia": "릴리아",
  "Lissandra": "리산드라",
  "Lucian": "루시안",
  "Lulu": "룰루",
  "Lux": "럭스",
  "Malphite": "말파이트",
  "Malzahar": "말자하",
  "Maokai": "마오카이",
  "MasterYi": "마스터이",
  "Milio": "밀리오",
  "MissFortune": "미스포츈",
  "Mordekaiser": "모데카이저",
  "Morgana": "모르가나",
  "Naafiri": "나피리",
  "Nami": "나미",
  "Nasus": "나서스",
  "Nautilus": "노틸러스",
  "Neeko": "니코",
  "Nidalee": "니달리",
  "Nilah": "닐라",
  "Nocturne": "녹턴",
  "Nunu&Willump": "누누와윌럼프",
  "Olaf": "올라프",
  "Orianna": "오리아나",
  "Ornn": "오른",
  "Pantheon": "판테온",
  "Poppy": "뽀삐",
  "Pyke": "파이크",
  "Qiyana": "키아나",
  "Quinn": "퀸",
  "Rakan": "라칸",
  "Rammus": "람머스",
  "RekSai": "렉사이",
  "Rell": "렐",
  "RenataGlasc": "레나타글라스크",
  "Renekton": "레넥톤",
  "Rengar": "렝가",
  "Riven": "리븐",
  "Rumble": "럼블",
  "Ryze": "라이즈",
  "Samira": "사미라",
  "Sejuani": "세주아니",
  "Senna": "세나",
  "Seraphine": "세라핀",
  "Sett": "세트",
  "Shaco": "샤코",
  "Shen": "쉔",
  "Shyvana": "쉬바나",
  "Singed": "신지드",
  "Sion": "사이온",
  "Sivir": "시비르",
  "Skarner": "스카너",
  "Smolder": "스몰더",
  "Sona": "소나",
  "Soraka": "소라카",
  "Swain": "스웨인",
  "Sylas": "사일러스",
  "Syndra": "신드라",
  "TahmKench": "탐켄치",
  "Taliyah": "탈리야",
  "Talon": "탈론",
  "Taric": "타릭",
  "Teemo": "티모",
  "Thresh": "쓰레쉬",
  "Tristana": "트리스타나",
  "Trundle": "트런들",
  "Tryndamere": "트린다미어",
  "TwistedFate": "트위스티드페이트",
  "Twitch": "트위치",
  "Udyr": "우디르",
  "Urgot": "우르곳",
  "Varus": "바루스",
  "Vayne": "베인",
  "Veigar": "베이가",
  "VelKoz": "벨코즈",
  "Vex": "벡스",
  "Vi": "바이",
  "Viego": "비에고",
  "Viktor": "빅토르",
  "Vladimir": "블라디미르",
  "Volibear": "볼리베어",
  "Warwick": "워윅",
  "Wukong": "오공",
  "Xayah": "자야",
  "Xerath": "제라스",
  "XinZhao": "신짜오",
  "Yasuo": "야스오",
  "Yone": "요네",
  "Yorick": "요릭",
  "Yuumi": "유미",
  "Zac": "자크",
  "Zed": "제드",
  "Zeri": "제리",
  "Ziggs": "직스",
  "Zilean": "질리언",
  "Zoe": "조이",
  "Zyra": "자이라"
  // ⚠️ 필요하면 계속 추가 가능
};

// 🔹 변환 유틸 함수
export function translateTier(tier) {
  return tierMap[tier] || tier;
}

export function translatePosition(pos) {
  return positionMap[pos] || pos;
}

export function translateChampion(champ) {
  return championMap[champ] || champ;
}
